// Single source of truth for `.zap/` — the per-project directory that
// houses ZAP's working artifacts inside whatever workspace the portal is
// pointed at.
//
// The portal runs against arbitrary project trees, so the tooling that
// needs space on disk (the `trash` store today; notes, inbox, and
// friends later) must not scatter top-level dot-dirs across the host
// repo — each new one would otherwise need its own ignore entry and is
// an easy spot to forget. Instead everything lives under one parent dir.
//
// `.zap/` is modeled on `.github/`: a stable, brand-named namespace that
// can hold BOTH committed config (reserved for future use) AND ephemeral
// junk. The two are kept apart by a single rule — everything ephemeral
// lives under `.zap/scratch/`, and a self-contained `.zap/.gitignore`
// (see `ensureZapGitignore`) ignores only `scratch/`, leaving the rest
// of the dir trackable. That nested ignore means a host project never
// has to touch its own root `.gitignore` to keep our scratch out of
// source control.
//
// The name is `.zap` after the project (Zestier's AI Portal) — a
// distinctive brand token rather than a generic word like `.agent`, so
// it is very unlikely to collide with directories another tool already
// owns in the same checkout. (Note: this is deliberately NOT called a
// "workdir" — that term already means the project tree the SDK runs
// against, see ../workdir.ts.) The `ZAP_DIR` env var provides an escape
// hatch for the rare project that still clashes.

import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";

const DEFAULT_ZAP_DIR = ".zap";

// Name of the single subdir under `.zap/` that holds ephemeral, never-
// committed artifacts. The auto-generated `.zap/.gitignore` ignores
// exactly this.
const SCRATCH_DIR_NAME = "scratch";

// A valid override is a single, plain path segment: not empty, no path
// separators, no `..`, no absolute paths, no NUL. Anything else falls
// back to the default so a fat-fingered env var can never relocate the
// store outside the workspace or nest it somewhere surprising.
function sanitize(raw: string | undefined): string {
  if (!raw) return DEFAULT_ZAP_DIR;
  const trimmed = raw.trim();
  if (trimmed === "" || trimmed === "." || trimmed === "..")
    return DEFAULT_ZAP_DIR;
  if (
    trimmed.includes("/") ||
    trimmed.includes("\\") ||
    trimmed.includes("\0")
  ) {
    return DEFAULT_ZAP_DIR;
  }
  return trimmed;
}

/**
 * The workspace-relative name of ZAP's per-project directory (default
 * `.zap`, overridable via `ZAP_DIR`). Resolved lazily on each call so
 * tests can set/clear the env var per case.
 */
export function zapDir(env: NodeJS.ProcessEnv = process.env): string {
  return sanitize(env.ZAP_DIR);
}

/**
 * Workspace-relative path of a named entry directly under `.zap/`, e.g.
 * `zapSubdir('config.json')` -> `.zap/config.json`. For ephemeral
 * artifacts use {@link scratchSubdir} instead so they land under the
 * ignored `scratch/` tree.
 */
export function zapSubdir(
  name: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return `${zapDir(env)}/${name}`;
}

/**
 * Workspace-relative path of the ephemeral scratch root, e.g.
 * `.zap/scratch`. Everything under here is covered by the generated
 * `.zap/.gitignore` and must be treated as disposable.
 */
export function scratchDir(env: NodeJS.ProcessEnv = process.env): string {
  return `${zapDir(env)}/${SCRATCH_DIR_NAME}`;
}

/**
 * Workspace-relative path of a named tenant inside the scratch root, e.g.
 * `scratchSubdir('trash')` -> `.zap/scratch/trash`.
 */
export function scratchSubdir(
  name: string,
  env: NodeJS.ProcessEnv = process.env,
): string {
  return `${scratchDir(env)}/${name}`;
}

const ZAP_GITIGNORE_BODY = `# Generated by ZAP. Delete to manage these ignores yourself.
/${SCRATCH_DIR_NAME}/
`;

/**
 * Ensure the host workspace ignores ZAP's ephemeral scratch area without
 * requiring edits to the project's own root `.gitignore`: drop a
 * self-contained `<zapDir>/.gitignore` that ignores only `scratch/`,
 * leaving the rest of the dir trackable. Created once and never
 * clobbered (the `wx` flag fails if it already exists, so a user's
 * customized copy is preserved). Safe to call on every scratch write.
 */
export async function ensureZapGitignore(
  workspaceRoot: string,
  env: NodeJS.ProcessEnv = process.env,
): Promise<void> {
  const dir = join(workspaceRoot, zapDir(env));
  await mkdir(dir, { recursive: true });
  try {
    await writeFile(join(dir, ".gitignore"), ZAP_GITIGNORE_BODY, {
      flag: "wx",
    });
  } catch (e) {
    // Already present (ours or a user's) — leave it untouched. Only a
    // genuine write failure should surface.
    if ((e as NodeJS.ErrnoException).code !== "EEXIST") throw e;
  }
}
