// Portal configuration belongs to the server process. Forwarding it to a
// project subprocess lets a nested portal command reuse the live database and
// exposes server credentials to commands and Git hooks.

export const PORTAL_ENV_NAMES = [
	'HOST',
	'PORT',
	'DATA_DIR',
	'PROJECT_ROOT',
	'ALLOWED_WORKDIRS',
	'WORKTREE_ROOT',
	'WORKTREE_CREATE_TIMEOUT_MS',
	'WORKTREE_MAX_LEASES_PER_CONVERSATION',
	'WORKTREE_MAX_LEASES_PER_USER',
	'WORKTREE_LEASE_TTL_MS',
	'LOG_LEVEL',
	'AUTH_MODE',
	'SESSION_SECRET',
	'SESSION_TTL_SECONDS',
	'ENCRYPTION_KEY',
	'I_KNOW_THIS_IS_LOCAL',
	'I_KNOW_THIS_IS_NETWORK_ACCESSIBLE',
	'GITHUB_CLIENT_ID',
	'GITHUB_CLIENT_SECRET',
	'ALLOWED_GITHUB_LOGINS',
	'REDEPLOY_ADMIN_GITHUB_LOGINS',
	'SHARED_SECRET',
	'COPILOT_GITHUB_TOKEN',
	'COPILOT_CONTEXT_TIER',
	'COPILOT_SDK_CALL_TIMEOUT_MS',
	'COPILOT_CLI_URL',
	'COPILOT_CONNECTION_TOKEN',
	'DEFAULT_BACKEND_PROVIDER',
	'ZAP_PROVIDERS_JSON',
	'DEFAULT_MODEL',
	'CLAUDE_AGENT_BASE_URL',
	'CLAUDE_AGENT_API_KEY',
	'CLAUDE_AGENT_MAX_TURNS',
	'OPENAI_COMPATIBLE_BASE_URL',
	'OPENAI_COMPATIBLE_API_KEY',
	'OPENAI_COMPATIBLE_MAX_TOOL_ITERATIONS',
	'OPENAI_COMPATIBLE_CONTEXT_RESTORE_MESSAGES',
	'OPENAI_COMPATIBLE_CONTEXT_TOKEN_LIMIT',
	'OPENAI_COMPATIBLE_TEMPERATURE',
	'OPENAI_COMPATIBLE_TOP_P',
	'OPENAI_COMPATIBLE_PRESENCE_PENALTY',
	'OPENAI_COMPATIBLE_FREQUENCY_PENALTY',
	'LMSTUDIO_BASE_URL',
	'LMSTUDIO_API_KEY',
	'MEMORY_EXTRACTOR_BACKEND',
	'MEMORY_EXTRACTOR_MODEL',
	'MEMORY_EXTRACTOR_TIMEOUT_MS',
	'MEMORY_EXTRACTOR_MAX_INPUT_CHARS',
	'MEMORY_EXTRACTOR_MAX_TOOL_ITERATIONS',
	'MEMORY_EXTRACTOR_MAX_WALLCLOCK_MS',
	'MEMORY_EXTRACTOR_WATCHDOG_GRACE_MS',
	'MEMORY_EXTRACTOR_TOOL_CHOICE',
	'MEMORY_EXTRACTOR_MAX_FAILED_CALL_NUDGES',
	'MEMORY_OPEN_LOOP_MAX_IDLE_TURNS',
	'MEMORY_LOG_RETENTION_MAX_EVENTS',
	'MEMORY_MAINTENANCE_INTERVAL_MIN',
	'MEMORY_PRIME_MAIN_MODEL',
	'ADVERSARY_SHADOW_MODEL',
	'ADVERSARY_SHADOW_BACKEND',
	'ADVERSARY_SHADOW_TIMEOUT_MS',
	'ADVERSARY_SHADOW_MAX_ARG_CHARS',
	'ADVERSARY_SHADOW_MAX_IN_FLIGHT',
	'IDLE_TIMEOUT_MIN',
	'MAX_CONCURRENT_SESSIONS',
	'TURN_ABORT_FINALIZE_DEADLINE_MS',
	'ENABLE_REDEPLOY',
	'COPILOT_STUB',
	'PI_MODEL',
	'PI_STUB',
	'ANTHROPIC_API_KEY',
	'ANTHROPIC_OAUTH_TOKEN',
	'OPENAI_API_KEY',
	'AZURE_OPENAI_API_KEY',
	'DEEPSEEK_API_KEY',
	'GEMINI_API_KEY',
	'GOOGLE_CLOUD_API_KEY',
	'MISTRAL_API_KEY',
	'GROQ_API_KEY',
	'CEREBRAS_API_KEY',
	'OPENROUTER_API_KEY',
	'DB_MIGRATIONS_DIR',
	'ZAP_DEPLOYED_AT'
] as const;

const PORTAL_ENV_SET = new Set<string>(PORTAL_ENV_NAMES);

export function isolatedChildEnv(
	source: NodeJS.ProcessEnv = process.env,
	overrides: NodeJS.ProcessEnv = {}
): NodeJS.ProcessEnv {
	const env: NodeJS.ProcessEnv = {};
	for (const [name, value] of Object.entries(source)) {
		if (!PORTAL_ENV_SET.has(name) && value !== undefined) env[name] = value;
	}
	for (const [name, value] of Object.entries(overrides)) {
		if (value === undefined) delete env[name];
		else env[name] = value;
	}
	return env;
}
