-- 068_adversary_model_settings.sql
--
-- Move the Phase 0 adversary shadow off a server-wide env switch and onto the
-- same three-layer configuration every other model-backed background feature
-- uses: env default, a SEED-ONLY user setting, and a per-conversation column.
--
-- Precedence at runtime is exactly the memory extractor's: the conversation
-- column wins, else the env default. `default_adversary_model` is copied onto
-- new conversations at creation and never re-read, so changing it does not
-- retroactively alter existing ones — and clearing a conversation's column is
-- a real "stop reviewing this conversation" rather than a silent re-inherit of
-- the user default. That last property is load-bearing: the reviewer sends tool
-- arguments to a third-party endpoint, so per-conversation opt-out must work
-- even for a user who set a default.
--
-- Why this is not an operator-only knob (the original shape):
--   * The data-egress gate is already `OPENAI_COMPATIBLE_BASE_URL`, an operator
--     setting. A user enabling the shadow only sends their OWN conversations'
--     tool arguments to a provider the operator has already configured — the
--     same thing the model-backed memory extractor does with conversation
--     content, and that is a user setting.
--   * The adversary refuses to run when its model equals the conversation's
--     agent model (shared weights = shared blind spots). With one global value
--     that guard is unfixable per conversation: point it at a model someone
--     happens to be using and the shadow silently disables itself there.
--   * Comparing two adversary models is the obvious next experiment, and
--     `experiment_key` already stratifies on model — but a single env value
--     cannot run two concurrently.
--
-- There is deliberately no separate on/off flag. A configured adversary model
-- IS the enablement, mirroring `isModelBackedExtractorConfigured`; two switches
-- that can disagree is a bug surface, not a feature. NULL everywhere (the
-- default) means the shadow stays off, so this migration changes no behaviour.

ALTER TABLE user_settings ADD COLUMN default_adversary_model TEXT;
ALTER TABLE conversations ADD COLUMN adversary_model TEXT;
